app:
  restart: "unless-stopped"
  image: php:7.4
  command: php -S 0.0.0.0:8080 /tuliosj-starcorp/index.php
  ports:
    - "8080:8080"
  working_dir: /tuliosj-starcorp
  volumes:
    - .:/tuliosj-starcorp

composer:
  restart: "no"
  image: composer:latest
  command: install
  working_dir: /tuliosj-starcorp
  volumes:
    - .:/tuliosj-starcorp

tests:
  restart: "no"
  image: php:7.4
  command: php vendor/bin/phpunit tests/
  working_dir: /tuliosj-starcorp
  volumes:
    - .:/tuliosj-starcorp
